# Configuració  de QVistaWeb - Entorn d'INTEGRACIÓ

gisquick:
  debug: true
  language: ca-es
  projectsRoot: c:/gisquick-int/publish
  mapserverURL: http://localhost:8080/cgi-bin/qgis_mapserv.fcgi.exe
  projectSizeLimit: 100M
  accountStorageLimit: 1G

auth:
  sessionExpiration: 24h
  secretKey: clau-secreta-integracio

web:
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 120s
  shutdownTimeout: 20s
  siteURL: http://127.0.0.1:82
  apiHost: 0.0.0.0:5000

postgres:
  user: postgres
  password: nexus
  host: localhost
  name: postgres_int
  port: 5433

redis:
  addr: localhost:6379
  db: 2  # Cada entorn utilitza una BD Redis diferent